# Generated by Django 4.1.5 on 2023-01-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='office_id',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='room_id',
            new_name='room',
        ),
    ]
