# Generated by Django 4.1.5 on 2023-01-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_office_id_room_office_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='number_of_rooms',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_seats',
            field=models.IntegerField(default=10),
        ),
    ]
