# Generated by Django 4.1.5 on 2023-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_seat_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='end_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seat',
            name='start_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
