# Generated by Django 4.1.5 on 2023-01-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_seat_end_booking_alter_seat_start_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='start_booking',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
