# Generated by Django 4.1.5 on 2023-01-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_seat_start_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='number_of_seats',
            new_name='free_seats',
        ),
        migrations.RemoveField(
            model_name='office',
            name='number_of_rooms',
        ),
    ]
