# Generated by Django 4.1.5 on 2023-01-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_number_of_seats_room_free_seats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='free_seats',
            field=models.IntegerField(),
        ),
    ]
