# Generated by Django 4.1.5 on 2023-01-29 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_room_free_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='free_seats',
            field=models.IntegerField(default=0),
        ),
    ]
