# Generated by Django 4.1.5 on 2023-01-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_room_free_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='start_booking',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
